version: '3.5'
services:
  app:
    image: php:7.4-apache
    container_name: clean-architecture-app
    volumes:
      - ./:/var/www/html
    ports:
      - '80:80'
      - '443:443'
    links:
      - mysql
    networks:
      - clean-architecture-networks
  mysql:
    image: mysql:5.7
    container_name: clean-architecture-db
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret_user
      MYSQL_DATABASE: secret_password
    networks:
      - clean-architecture-networks
    volumes:
      - ./.docker/data:/var/lib/mysql

networks:
  clean-architecture-networks:
    driver: bridge